### ISSUE TITLE
Complete UA Backup

### ISSUE THREAD

**Issue by shilojones** [aliasoblomov/Universal-Analytics-to-BigQuery#10]
Thank you so much for making this script.  I went through your article on Medium and then installed the script and I was able to get it it to work.  

Here is the issue I am wrestling with now.  I've got about 50 UA accounts that I want to backup data for and deciding the dimensions and metrics to use is the big work ahead of me.  We have a client that had UA 360 and I guess there is a built in backfill utility that helped them migrate their data to BigQuery.  I've attached the schema that was the output of that utility.
[ua_schema - ua_schema.csv](https://github.com/aliasoblomov/Universal-Analytics-to-BigQuery/files/15504646/ua_schema.-.ua_schema.csv)

It seems comprehensive (although I didn't see data around internal search for example) and I think it make sense to backup data in this way.  I also considered backing up the data into separate table for each scope (User, Session, Hit, Product).

It's maddening that Google didn't make this easy for everyone since the majority of the Universal Analytics users would likely be creating GCP accounts to move their data into BigQuery.

Would love to help provide people with a free (or mostly free) way of getting all of the data they'd want from UA.

**Comment by aliasoblomov** [comment]
Hi, thanks for your feedback , using this code we can not retrive feilds seprately for each scope and then have many joins , the better choice is using Bigquery connection that exists for GA360 , also i close this issue , because is irrelevant with repository , but you can continue this conversation in linkedin : 
https://www.linkedin.com/in/ali-iz/
